import type { Node as MorphNode } from "ts-morph";
import type { SourceFile, TypeChecker } from "ts-morph";

export type FileRole =
  | "guard"
  | "facade"
  | "store"
  | "context"
  | "service"
  | "component"
  | "page"
  | "hook"
  | "controller"
  | "repository"
  | "pipe"
  | "directive"
  | "routes"
  | "model"
  | "util"
  | "unknown";

export interface ExtractedContext extends Omit<
  SemanticContext,
  "title" | "meta" | "metrics" | "role" | "summary"
> {
  relatedContextFiles: string[];
}

export interface CPLintAdapter {
  name: string;
  classify(file: SourceFile): FileRole;
  extract(
    file: SourceFile,
    checker: TypeChecker,
    config: Config,
  ): ExtractedContext;
}

export type ManualBlockKey =
  | "purpose"
  | "decisions"
  | "constraints"
  | "known-pitfalls"
  | "not-in-scope"
  | "open-questions";

export type ManualDefaults = Record<ManualBlockKey, string>;

export type ManualBlocks = {
  [key in ManualBlockKey]?: string;
} & Record<string, string | undefined>;

export type ClassifierRule = {
  name?: string;
  kind?: string;
  label: string;
};

export type ImportRoleRule = {
  module?: string;
  label: string;
};

export type FlowBoundaryRule = {
  matchExpr?: string;
  matchFile?: string;
  label: string;
};

export type Config = {
  tsConfigFilePath: string;
  outputFileName: string;
  includePrivateTypes: boolean;
  maxTypeFields: number;
  maxFlowSteps: number;
  maxReferenceFiles: number;
  manualDefaults: ManualDefaults;
  classifiers: ClassifierRule[];
  importRoleRules: ImportRoleRule[];
  flowBoundaryRules: FlowBoundaryRule[];
  diagram?: boolean;
};

export const DEFAULT_CONFIG: Config = {
  tsConfigFilePath: "tsconfig.json",
  outputFileName: "{base}.context.ai.yaml",
  includePrivateTypes: false,
  maxTypeFields: 12,
  maxFlowSteps: 8,
  maxReferenceFiles: 8,
  manualDefaults: {
    purpose:
      "- Required. Main responsibility of this file/component/module; describe what it does and its role in the architecture.",
    decisions:
      "- Required. Key architectural/business decisions and rationale that are not obvious from reading the code.",
    constraints:
      "- Required. Rules, invariants, contracts, or assumptions that future changes must preserve.",
    "known-pitfalls":
      "- Optional. Non-obvious behaviors, edge cases, side effects, performance concerns, or common implementation mistakes; delete if empty.",
    "not-in-scope":
      "- Optional. Responsibilities intentionally excluded from this file and handled elsewhere; delete if empty.",
    "open-questions":
      "- Optional. Known uncertainties, pending decisions, technical debt, or areas requiring future investigation; delete if empty.",
  },
  classifiers: [],
  importRoleRules: [],
  flowBoundaryRules: [],
};

export type EntryPoint = {
  name: string;
  kind: string;
  file: string;
};

/**
 * A single exported symbol in the public API.
 *
 * - `signature` — full call signature, e.g. `CardSectionTitle(title: string) → string`
 * - `flags`     — semantic tags inferred from the AST, e.g. ["exported", "pure", "async"]
 *
 * Replaces the old `kind | type` format which was ambiguous to LLMs.
 */
export type ApiSurfaceRow = {
  name: string;
  signature: string;
  flags: string[];
};

export type DependencyRow = {
  module: string;
  role: string;
  symbols: string[];
  type: string;
};

export type StateField = {
  name: string;
  type: string;
};

export type StateShapeRow = {
  name: string;
  fields: StateField[];
};

export type SemanticContext = {
  title: string;
  role: FileRole;
  /**
   * One-sentence AUTO summary of the file's primary export.
   * Generated by the AST — never edited manually.
   * Example: "Exported function component. Receives `title: string`, returns JSX. No side effects detected."
   */
  summary: string;
  meta: {
    generated: string;
    entry: string;
    related: string[];
  };
  entryPoints: EntryPoint[];
  apiSurface: ApiSurfaceRow[];
  deps: DependencyRow[];
  stateShape: StateShapeRow[];
  criticalFlow: string[];
  changeChecklist: string[];
};

export type ExportDeclRow = {
  exportName: string;
  decl: MorphNode;
};
