import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";
import { loadConfig } from "../../config/load-config.js";
import { resolveEntrypoint } from "../../core/utils/resolve-entrypoint.js";

export interface CompileOptions {
  interleave: boolean;
  output?: string;
}

// Roles considered noise for the LLM — the model already knows these from pre-training
const FRAMEWORK_ROLES = new Set([
  "framework",
  "reactive",
  "external",
  "builtin",
]);

// Placeholder prefixes generated by manualDefaults — not real content
const PLACEHOLDER_PREFIXES = ["Required.", "Optional."];

function isPlaceholder(value: unknown): boolean {
  if (!Array.isArray(value)) return false;
  return value.every((item) =>
    PLACEHOLDER_PREFIXES.some((prefix) => String(item).startsWith(prefix)),
  );
}

function parseList(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((v) => v !== null && v !== undefined && v !== "")
    .map(String);
}

function parseMap(value: unknown): Record<string, unknown> {
  if (!value || value === "none" || typeof value !== "object") return {};
  return value as Record<string, unknown>;
}

export async function contextCompiler(
  filePath: string,
  options: CompileOptions,
): Promise<string> {
  const config = await loadConfig();
  const resolvedPath = resolveEntrypoint(config.rootPath, filePath);

  console.log(`\n🧑‍🍳 Compiling context from: ${resolvedPath}`);
  console.log(`⚙️  Interleaving enabled: ${options.interleave}\n`);

  const rawYaml = fs.readFileSync(resolvedPath, "utf8");

  if (!options.interleave) {
    maybeWrite(rawYaml, resolvedPath, options.output, config.rootPath);
    return rawYaml;
  }

  const parsed = YAML.parse(rawYaml);
  const manual = parsed.manual || {};
  const auto = parsed.auto || {};

  // ── Fix #1: deps — guard against "none" string before filtering ───────────
  const rawDeps = auto["deps"];
  const localDeps =
    !rawDeps || rawDeps === "none" || typeof rawDeps !== "object"
      ? {}
      : Object.fromEntries(
          Object.entries(rawDeps as Record<string, unknown>).filter(
            ([, v]) => !FRAMEWORK_ROLES.has((v as any)?.role),
          ),
        );

  // ── Fix #2: change-checklist — guard against "none" string ───────────────
  const rawChecklist = auto["change-checklist"];
  const changeChecklist = parseList(rawChecklist);

  // ── Fix #4: related — filter "none" sentinel ──────────────────────────────
  const rawRelated = auto.meta?.related || [];
  const related = parseList(rawRelated).filter((r) => r !== "none");

  // ── Build global block ─────────────────────────────────────────────────────
  const interleavedPayload: Record<string, any> = {
    "# cplint-config": "compiled-interleaved-view",
    global: {
      purpose: isPlaceholder(manual.purpose) ? "-" : manual.purpose || "-",
      not_in_scope: isPlaceholder(manual["not-in-scope"])
        ? "-"
        : manual["not-in-scope"] || "-",
      open_questions: isPlaceholder(manual["open-questions"])
        ? "-"
        : manual["open-questions"] || "-",
      meta: {
        ...(auto.meta || {}),
        related: related.length ? related : [],
      },
      summary: auto.summary || "",
      deps: localDeps,
      ...(changeChecklist.length
        ? { "change-checklist": changeChecklist }
        : {}),
    },
    scopes: {},
  };

  // ── Fix #5: entry-points — only include when no scopes will be built ───────
  // (added after identifiers are resolved below)

  // ── Build per-symbol scopes ────────────────────────────────────────────────
  const apiSurface = auto["api-surface"];
  const identifiers =
    !apiSurface || apiSurface === "none" || typeof apiSurface !== "object"
      ? []
      : Object.keys(apiSurface);

  // Fix #5: only emit entry-points in global when there are no scopes
  if (!identifiers.length) {
    const rawEntryPoints = auto["entry-points"];
    if (rawEntryPoints && rawEntryPoints !== "none") {
      interleavedPayload.global["entry-points"] = rawEntryPoints;
    }
  }

  for (const id of identifiers) {
    const criticalFlow = filterArrayByToken(auto["critical-flow"], id);
    const stateShape = findStateShape(parseMap(auto["state-shape"]), id);
    const decisions = filterRealContent(
      filterArrayByToken(manual.decisions, id),
    );
    const constraints = filterRealContent(
      filterArrayByToken(manual.constraints, id),
    );
    const pitfalls = filterRealContent(
      filterArrayByToken(manual["known-pitfalls"], id),
    );

    const scopeBlock: Record<string, any> = {
      "api-surface": { [id]: (apiSurface as Record<string, unknown>)[id] },
    };

    if (criticalFlow.length) scopeBlock["critical-flow"] = criticalFlow;
    if (stateShape) scopeBlock["state-shape"] = stateShape;
    if (decisions.length) scopeBlock["decisions"] = decisions;
    if (constraints.length) scopeBlock["constraints"] = constraints;
    if (pitfalls.length) scopeBlock["known-pitfalls"] = pitfalls;

    interleavedPayload.scopes[id] = scopeBlock;
  }

  // ── No scopes: move non-placeholder manual rules to global ────────────────
  if (!identifiers.length) {
    const decisions = filterRealContent(parseList(manual.decisions));
    const constraints = filterRealContent(parseList(manual.constraints));
    const pitfalls = filterRealContent(parseList(manual["known-pitfalls"]));

    if (decisions.length) interleavedPayload.global.decisions = decisions;
    if (constraints.length) interleavedPayload.global.constraints = constraints;
    if (pitfalls.length) interleavedPayload.global["known-pitfalls"] = pitfalls;
  }

  // ── Fix #3: unmapped_rules — skip placeholders ────────────────────────────
  const fallbackDecisions = filterRealContent(
    filterUnmappedTokens(manual.decisions, identifiers),
  );
  const fallbackConstraints = filterRealContent(
    filterUnmappedTokens(manual.constraints, identifiers),
  );
  const fallbackPitfalls = filterRealContent(
    filterUnmappedTokens(manual["known-pitfalls"], identifiers),
  );

  if (
    fallbackDecisions.length ||
    fallbackConstraints.length ||
    fallbackPitfalls.length
  ) {
    interleavedPayload.global.unmapped_rules = {
      ...(fallbackDecisions.length ? { decisions: fallbackDecisions } : {}),
      ...(fallbackConstraints.length
        ? { constraints: fallbackConstraints }
        : {}),
      ...(fallbackPitfalls.length
        ? { "known-pitfalls": fallbackPitfalls }
        : {}),
    };
  }

  const compiled = YAML.stringify(interleavedPayload, { indent: 2 });

  // ── Token estimate (1 token ≈ 4 chars — reasonable heuristic for code/YAML)
  const estimatedTokens = Math.ceil(compiled.length / 4);
  console.log(`📊 Estimated tokens: ~${estimatedTokens}`);

  maybeWrite(compiled, resolvedPath, options.output, config.rootPath);

  return compiled;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Filter out placeholder items generated by manualDefaults.
 * "Required. ..." and "Optional. ..." are default hints, not real content.
 */
function filterRealContent(items: string[]): string[] {
  return items.filter(
    (item) => !PLACEHOLDER_PREFIXES.some((prefix) => item.startsWith(prefix)),
  );
}

/**
 * Filter list items that mention the given token by word boundary.
 */
function filterArrayByToken(list: unknown, token: string): string[] {
  if (!Array.isArray(list)) return [];
  const regex = new RegExp(`\\b${token}\\b|\\.${token}\\b`);
  return list.filter((item) => regex.test(String(item)));
}

/**
 * Returns items from list that don't mention any known identifier.
 */
function filterUnmappedTokens(list: unknown, identifiers: string[]): string[] {
  if (!Array.isArray(list)) return [];
  return list.filter((item) => {
    const line = String(item);
    return !identifiers.some((id) => line.includes(id));
  });
}

/**
 * Looks up state-shape by exact key first, then by prefix.
 */
function findStateShape(
  stateShape: Record<string, unknown>,
  id: string,
): unknown {
  if (!stateShape || !Object.keys(stateShape).length) return null;
  if (stateShape[id]) return stateShape[id];
  const prefixKey = Object.keys(stateShape).find((k) => k.startsWith(`${id}.`));
  return prefixKey ? stateShape[prefixKey] : null;
}

/**
 * Writes the compiled output to a file if --output was specified.
 */
function maybeWrite(
  content: string,
  sourcePath: string,
  outputPath?: string,
  rootPath?: string,
): void {
  if (!outputPath) return;

  const cleanOutput = outputPath.replace(/^\//, "");
  const base = rootPath ? path.resolve(process.cwd(), rootPath) : process.cwd();

  const resolved = path.resolve(base, cleanOutput);

  let finalPath = resolved;
  if (fs.existsSync(resolved) && fs.statSync(resolved).isDirectory()) {
    const baseName = path.basename(sourcePath).replace(".cplint.yaml", "");
    finalPath = path.join(resolved, `${baseName}.compiled.yaml`);
  }

  fs.mkdirSync(path.dirname(finalPath), { recursive: true });
  fs.writeFileSync(finalPath, content, "utf8");
  console.log(`💾 Saved to: ${finalPath}`);
}
