import type { SourceFile } from "ts-morph";
import type {
  Config,
  ManualBlocks,
  SemanticContext,
} from "../../types/index.js";
import { renderMeta } from "./render-meta.js";
import { renderEntryPoints } from "./render-entrypoints.js";
import { renderApiSurface } from "./render-api-surface.js";
import { renderDeps } from "./render-deps.js";
import { renderCriticalFlow } from "./render-critical-flow.js";
import { renderChecklist } from "./render-checklist.js";
import { renderAutoBlock, renderManualBlock } from "./render-blocks.js";
import { renderStateShape } from "./render-state-shape.js";

export function renderDocument(
  context: SemanticContext,
  config: Config,
  manualBlocks: ManualBlocks,
  _sourceFile: SourceFile,
): string {
  const manual = {
    ...config.manualDefaults,
    ...manualBlocks,
  };

  const sections: string[] = [
    "<!-- Generated by CPLint. Edit only MANUAL blocks. -->",
    "",

    // ── meta ──────────────────────────────────────────────────────────────
    "## meta",
    renderAutoBlock("meta", renderMeta(context.meta, context.role)),
    "",
    renderManualBlock("meta", manual.meta),
    "",

    // ── summary ───────────────────────────────────────────────────────────
    "## summary",
    renderAutoBlock("summary", context.summary),
    "",

    // ── purpose (MANUAL — always emitted so the dev can fill it) ──────────
    "## purpose",
    renderManualBlock("purpose", manual.purpose),
    "",

    // ── entry-points ──────────────────────────────────────────────────────
    "## entry-points",
    renderAutoBlock(
      "entry-points",
      renderEntryPoints(context.entryPoints) || "- none",
    ),
    "",

    // ── api-surface ───────────────────────────────────────────────────────
    "## api-surface",
    renderAutoBlock("api-surface", renderApiSurface(context.apiSurface)),
    "",

    // ── deps ──────────────────────────────────────────────────────────────
    "## deps",
    renderAutoBlock("deps", renderDeps(context.deps)),
    "",

    // ── state-shape (AUTO — omit when empty, no value for the dev here) ───
    ...(context.stateShape.length
      ? [
          "## state-shape",
          renderAutoBlock("state-shape", renderStateShape(context.stateShape)),
          "",
        ]
      : []),

    // ── critical-flow (AUTO — omit when empty) ────────────────────────────
    ...(context.criticalFlow.length
      ? [
          "## critical-flow",
          renderAutoBlock(
            "critical-flow",
            renderCriticalFlow(context.criticalFlow, config),
          ),
          "",
        ]
      : []),

    // ── decisions (MANUAL — always emitted so the dev can fill it) ────────
    "## decisions",
    renderManualBlock("decisions", manual.decisions),
    "",

    // ── constraints (MANUAL — always emitted so the dev can fill it) ──────
    "## constraints",
    renderManualBlock("constraints", manual.constraints),
    "",

    // ── known-pitfalls (MANUAL — always emitted so the dev can fill it) ───
    "## known-pitfalls",
    renderManualBlock("known-pitfalls", manual["known-pitfalls"]),
    "",

    // ── not-in-scope (MANUAL — always emitted so the dev can fill it) ─────
    "## not-in-scope",
    renderManualBlock("not-in-scope", manual["not-in-scope"]),
    "",

    // ── change-checklist (AUTO) ───────────────────────────────────────────
    "## change-checklist",
    renderAutoBlock(
      "change-checklist",
      renderChecklist(context.changeChecklist),
    ),
    "",

    // ── open-questions (MANUAL — always emitted) ──────────────────────────
    "## open-questions",
    renderManualBlock("open-questions", manual["open-questions"]),
    "",
  ];

  return sections
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()
    .concat("\n");
}
