const MODELS = [
  { name: "Claude 3.5 Sonnet", window: 200000 },
  { name: "GPT-4o", window: 128000 },
  { name: "Gemini 1.5 Pro", window: 1000000 },
  { name: "Llama 3.1", window: 128000 },
];

const FILES = __INITIAL_DATA__;
let warnThreshold = __WARN_THRESHOLD__;

let currentModel = 0;
let sortMode = "tokens";

const fmt = (n) => Math.round(n).toLocaleString("en-US");

function severity(toks) {
  if (toks >= warnThreshold * 1.5) return "danger";
  if (toks >= warnThreshold) return "warn";
  return "ok";
}

function renderMetrics() {
  const totalToks = FILES.reduce((a, f) => a + f.tokens, 0);
  const overWarn = FILES.filter((f) => severity(f.tokens) === "warn").length;
  const overDng = FILES.filter((f) => severity(f.tokens) === "danger").length;
  const model = MODELS[currentModel];
  const usedPct = Math.min(100, Math.round((totalToks / model.window) * 100));

  document.getElementById("metrics").innerHTML = `
    <div class="metric">
      <div class="metric-label">total raw source weight</div>
      <div class="metric-value">${fmt(totalToks)}</div>
      <div class="metric-sub">total tokens (*estimated GPT-compatible tokens)</div>
    </div>
    <div class="metric">
      <div class="metric-label">context window used</div>
      <div class="metric-value ${usedPct > 70 ? "warn" : "ok"}">${usedPct}%</div>
      <div class="metric-sub">${model.name}</div>
    </div>
    <div class="metric">
      <div class="metric-label">needs attention</div>
      <div class="metric-value ${overWarn > 0 ? "warn" : "ok"}">${overWarn}</div>
      <div class="metric-sub">exceeded threshold</div>
    </div>
    <div class="metric">
      <div class="metric-label">critical status</div>
      <div class="metric-value ${overDng > 0 ? "danger" : "ok"}">${overDng}</div>
      <div class="metric-sub">requires cplint.yaml</div>
    </div>`;
}

function renderFiles() {
  const maxTokens = Math.max(...FILES.map((f) => f.tokens), 1);

  document.getElementById("file-list").innerHTML = [...FILES]
    .sort((a, b) => {
      if (sortMode === "name") return a.name.localeCompare(b.name);
      return b.tokens - a.tokens;
    })
    .map((f) => {
      const s = severity(f.tokens);
      const pWidth = Math.round((f.tokens / maxTokens) * 100);

      return `
      <div class="file-row">
        <div class="severity-dot dot-${s}"></div>
        <span class="file-name">${f.name}</span>
        <span class="file-pkg">${f.pkg}</span>
        <div class="bar-outer">
          <div class="bar-inner bar-${s}" style="width:${pWidth}%"></div>
        </div>
        <span class="tok-display ${s}">${fmt(f.tokens)}</span>
      </div>`;
    })
    .join("");
}

function renderAlerts() {
  const alerts = [];
  FILES.forEach((f) => {
    const s = severity(f.tokens);
    if (s === "danger")
      alerts.push(
        `<div class="alert alert-danger">🚨 <strong>${f.name}</strong> is critical (${fmt(f.tokens)} tokens). Create a rules file immediately to scope context down.</div>`,
      );
    if (s === "warn")
      alerts.push(
        `<div class="alert alert-warn">⚠️ <strong>${f.name}</strong> has passed the safe threshold limit (${fmt(f.tokens)} tokens). Consider running cplint.</div>`,
      );
  });
  document.getElementById("alert-section").innerHTML =
    alerts.length === 0
      ? '<div class="no-alerts">✓ All scanned files are lightweight and safe for direct context payload transfer.</div>'
      : `<div class="alert-list">${alerts.join("")}</div>`;
}

function initDates() {
  const now = new Date();
  const dateStr =
    now.toLocaleDateString("en-US") +
    " · " +
    now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });
  document.getElementById("header-date").textContent = dateStr;
  document.getElementById("footer-date").textContent =
    "generated by cplint token-counter · " + dateStr;
}

function setupSlider() {
  const slider = document.getElementById("warn-slider");
  if (slider) {
    slider.value = warnThreshold;
    document.getElementById("warn-val").textContent = fmt(warnThreshold);
  }
}

function render() {
  renderMetrics();
  renderFiles();
  renderAlerts();
}

function setModel(idx, el) {
  currentModel = idx;
  document
    .querySelectorAll(".mtab")
    .forEach((t) => t.classList.remove("active"));
  el.classList.add("active");
  renderMetrics();
}

function setSort(mode, el) {
  sortMode = mode;
  document
    .querySelectorAll(".sort-btn")
    .forEach((t) => t.classList.remove("active"));
  el.classList.add("active");
  renderFiles();
}

function onThreshold() {
  warnThreshold = parseInt(document.getElementById("warn-slider").value);
  document.getElementById("warn-val").textContent = fmt(warnThreshold);
  render();
}

document.addEventListener("DOMContentLoaded", () => {
  initDates();
  setupSlider();
  render();
});
